# Generated by Django 5.0.1 on 2024-03-05 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('price_per_night', models.IntegerField()),
                ('hotel_img1', models.ImageField(upload_to='photos/hotels')),
                ('hotel_img2', models.ImageField(upload_to='photos/hotels')),
                ('descriptons', models.TextField()),
                ('slug', models.SlugField(default=None, max_length=100, unique=True)),
                ('county_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('customers', models.ManyToManyField(blank=True, related_name='booked_hotel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
