# Generated by Django 5.0.1 on 2024-03-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='county_name',
            new_name='country_name',
        ),
    ]
