# Generated by Django 5.0.1 on 2024-03-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0002_rename_county_name_hotel_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_img2',
        ),
    ]
